install! 'cocoapods',
  :share_schemes_for_development_pods => true

use_frameworks!

target 'healthvault-ios-sdk_Example' do
  platform :ios, '10.0'
  pod 'HealthVault', :path => '../'
  pod 'EncryptedCoreData', :inhibit_warnings => true, :git => 'https://github.com/project-imas/encrypted-core-data.git', :commit => 'b97ffaf2f' # xcode 9 workaround
  pod 'SQLCipher', :inhibit_warnings => true

  target 'healthvault-ios-sdk_Tests' do
    platform :ios, '10.0'
    inherit! :search_paths

    pod 'HealthVault/Tests', :path => '../'
    pod 'Kiwi', :inhibit_warnings => true
  end
end
