install! 'cocoapods',
  :share_schemes_for_development_pods => true

use_frameworks!

  target 'healthvault-ios-sdk_Example' do
    platform :ios, '8.0'
    pod ‘HealthVault’, :path => '../'

  target 'healthvault-ios-sdk_Tests' do
    platform :ios, '8.0'
    inherit! :search_paths

    pod 'Kiwi'
  end
end
