//
// MHVGoalsRecommendationsApi.m
// MHVLib
//
// Copyright (c) 2017 Microsoft Corporation. All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

/**
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import <Foundation/Foundation.h>
#import "MHVRemoteMonitoringClient.h"
#import "MHVClient.h"
#import "MHVGoalsRecommendationsApi.h"
#import "MHVGoalRecommendation.h"
#import "MHVGoalRecommendationInstance.h"
#import "MHVGoalRecommendationsResponse.h"
#import "MHVMicrosoftKhronosCloudCommonErrorsErrorResponse.h"
#import "MHVSystemObject.h"


@implementation MHVRemoteMonitoringClient (MHVGoalsRecommendationsApi)

NSString* kMHVGoalsRecommendationsApiErrorDomain = @"MHVGoalsRecommendationsApiErrorDomain";
NSInteger kMHVGoalsRecommendationsApiMissingParamErrorCode = 234513;

#pragma mark - Api Methods

///
/// Updates the goal recommendation to acknowledged state
/// 
///  @param goalRecommendationId The identifier of the goal recommendation to acknowledge. 
///
///  @returns MHVSystemObject*
///
+ (NSURLSessionTask*)acknowledgeGoalRecommendationWithGoalRecommendationId: (NSString*) goalRecommendationId
    completionHandler: (void (^ _Nonnull)(MHVSystemObject* _Nullable output, NSError* _Nullable error)) handler {
    // verify the required parameter 'goalRecommendationId' is set
    if (goalRecommendationId == nil) {
        NSParameterAssert(goalRecommendationId);
        if(handler) {
            NSDictionary * userInfo = @{NSLocalizedDescriptionKey : [NSString stringWithFormat:NSLocalizedString(@"Missing required parameter '%@'", nil),@"goalRecommendationId"] };
            NSError* error = [NSError errorWithDomain:kMHVGoalsRecommendationsApiErrorDomain code:kMHVGoalsRecommendationsApiMissingParamErrorCode userInfo:userInfo];
            handler(nil, error);
        }
        return nil;
    }

    NSMutableString* resourcePath = [NSMutableString stringWithFormat:@"/GoalRecommendations/{goalRecommendationId}/Acknowledge"];

    NSMutableDictionary *pathParams = [[NSMutableDictionary alloc] init];
    if (goalRecommendationId != nil) {
        pathParams[@"goalRecommendationId"] = goalRecommendationId;
    }

    NSMutableDictionary* queryParams = [[NSMutableDictionary alloc] init];

    id bodyParam = nil;
    NSMutableDictionary *formParams = [[NSMutableDictionary alloc] init];

    return [MHVRemoteMonitoringClient requestWithPath: resourcePath
                                    method: @"PUT"
                                pathParams: pathParams
                               queryParams: queryParams
                                formParams: formParams
                                      body: bodyParam
                                   toClass: [MHVSystemObject class]
                    //        responseType: [MHVSystemObject* class]
                           completionBlock: ^(id data, NSError *error) {
                                if(handler) {
                                    handler((MHVSystemObject*)data, error);
                                }
                            }];
}

///
/// Post a goal recommendation instance
/// 
///  @param goalRecommendation The instance of the goal recommendation to create. 
///
///  @returns MHVSystemObject*
///
+ (NSURLSessionTask*)addGoalRecommendationWithGoalRecommendation: (MHVGoalRecommendation*) goalRecommendation
    completionHandler: (void (^ _Nonnull)(MHVSystemObject* _Nullable output, NSError* _Nullable error)) handler {
    // verify the required parameter 'goalRecommendation' is set
    if (goalRecommendation == nil) {
        NSParameterAssert(goalRecommendation);
        if(handler) {
            NSDictionary * userInfo = @{NSLocalizedDescriptionKey : [NSString stringWithFormat:NSLocalizedString(@"Missing required parameter '%@'", nil),@"goalRecommendation"] };
            NSError* error = [NSError errorWithDomain:kMHVGoalsRecommendationsApiErrorDomain code:kMHVGoalsRecommendationsApiMissingParamErrorCode userInfo:userInfo];
            handler(nil, error);
        }
        return nil;
    }

    NSMutableString* resourcePath = [NSMutableString stringWithFormat:@"/GoalRecommendations"];

    NSMutableDictionary *pathParams = [[NSMutableDictionary alloc] init];

    NSMutableDictionary* queryParams = [[NSMutableDictionary alloc] init];

    id bodyParam = nil;
    NSMutableDictionary *formParams = [[NSMutableDictionary alloc] init];
    bodyParam = goalRecommendation;

    return [MHVRemoteMonitoringClient requestWithPath: resourcePath
                                    method: @"POST"
                                pathParams: pathParams
                               queryParams: queryParams
                                formParams: formParams
                                      body: bodyParam
                                   toClass: [MHVSystemObject class]
                    //        responseType: [MHVSystemObject* class]
                           completionBlock: ^(id data, NSError *error) {
                                if(handler) {
                                    handler((MHVSystemObject*)data, error);
                                }
                            }];
}

///
/// Delete a goal recommendation instance
/// 
///  @param goalRecommendationId The identifier of the goal recommendation to delete. 
///
///  @returns MHVSystemObject*
///
+ (NSURLSessionTask*)deleteGoalRecommendationWithGoalRecommendationId: (NSString*) goalRecommendationId
    completionHandler: (void (^ _Nonnull)(MHVSystemObject* _Nullable output, NSError* _Nullable error)) handler {
    // verify the required parameter 'goalRecommendationId' is set
    if (goalRecommendationId == nil) {
        NSParameterAssert(goalRecommendationId);
        if(handler) {
            NSDictionary * userInfo = @{NSLocalizedDescriptionKey : [NSString stringWithFormat:NSLocalizedString(@"Missing required parameter '%@'", nil),@"goalRecommendationId"] };
            NSError* error = [NSError errorWithDomain:kMHVGoalsRecommendationsApiErrorDomain code:kMHVGoalsRecommendationsApiMissingParamErrorCode userInfo:userInfo];
            handler(nil, error);
        }
        return nil;
    }

    NSMutableString* resourcePath = [NSMutableString stringWithFormat:@"/GoalRecommendations/{goalRecommendationId}"];

    NSMutableDictionary *pathParams = [[NSMutableDictionary alloc] init];
    if (goalRecommendationId != nil) {
        pathParams[@"goalRecommendationId"] = goalRecommendationId;
    }

    NSMutableDictionary* queryParams = [[NSMutableDictionary alloc] init];

    id bodyParam = nil;
    NSMutableDictionary *formParams = [[NSMutableDictionary alloc] init];

    return [MHVRemoteMonitoringClient requestWithPath: resourcePath
                                    method: @"DELETE"
                                pathParams: pathParams
                               queryParams: queryParams
                                formParams: formParams
                                      body: bodyParam
                                   toClass: [MHVSystemObject class]
                    //        responseType: [MHVSystemObject* class]
                           completionBlock: ^(id data, NSError *error) {
                                if(handler) {
                                    handler((MHVSystemObject*)data, error);
                                }
                            }];
}

///
/// Get an instance of a specific goal recommendation
/// 
///  @param goalRecommendationId The goal recommendation identifier. 
///
///  @returns MHVGoalRecommendationInstance*
///
+ (NSURLSessionTask*)getGoalRecommendationByIdWithGoalRecommendationId: (NSString*) goalRecommendationId
    completionHandler: (void (^ _Nonnull)(MHVGoalRecommendationInstance* _Nullable output, NSError* _Nullable error)) handler {
    // verify the required parameter 'goalRecommendationId' is set
    if (goalRecommendationId == nil) {
        NSParameterAssert(goalRecommendationId);
        if(handler) {
            NSDictionary * userInfo = @{NSLocalizedDescriptionKey : [NSString stringWithFormat:NSLocalizedString(@"Missing required parameter '%@'", nil),@"goalRecommendationId"] };
            NSError* error = [NSError errorWithDomain:kMHVGoalsRecommendationsApiErrorDomain code:kMHVGoalsRecommendationsApiMissingParamErrorCode userInfo:userInfo];
            handler(nil, error);
        }
        return nil;
    }

    NSMutableString* resourcePath = [NSMutableString stringWithFormat:@"/GoalRecommendations/{goalRecommendationId}"];

    NSMutableDictionary *pathParams = [[NSMutableDictionary alloc] init];
    if (goalRecommendationId != nil) {
        pathParams[@"goalRecommendationId"] = goalRecommendationId;
    }

    NSMutableDictionary* queryParams = [[NSMutableDictionary alloc] init];

    id bodyParam = nil;
    NSMutableDictionary *formParams = [[NSMutableDictionary alloc] init];

    return [MHVRemoteMonitoringClient requestWithPath: resourcePath
                                    method: @"GET"
                                pathParams: pathParams
                               queryParams: queryParams
                                formParams: formParams
                                      body: bodyParam
                                   toClass: [MHVGoalRecommendationInstance class]
                    //        responseType: [MHVGoalRecommendationInstance* class]
                           completionBlock: ^(id data, NSError *error) {
                                if(handler) {
                                    handler((MHVGoalRecommendationInstance*)data, error);
                                }
                            }];
}

///
/// Get a collection of all goal recommendations
/// 
///  @param goalTypes The goal types(e.g Steps, CaloriesBurned) filter. (optional)
///
///  @param goalWindowTypes The goal window types(e.g Daily, Weekly) filter. (optional)
///
///  @returns MHVGoalRecommendationsResponse*
///
+ (NSURLSessionTask*)getGoalRecommendationsWithGoalTypes: (NSString*) goalTypes
    goalWindowTypes: (NSString*) goalWindowTypes
    completionHandler: (void (^ _Nonnull)(MHVGoalRecommendationsResponse* _Nullable output, NSError* _Nullable error)) handler {
    NSMutableString* resourcePath = [NSMutableString stringWithFormat:@"/GoalRecommendations"];

    NSMutableDictionary *pathParams = [[NSMutableDictionary alloc] init];

    NSMutableDictionary* queryParams = [[NSMutableDictionary alloc] init];
    if (goalTypes != nil) {
        queryParams[@"goalTypes"] = goalTypes;
    }
    if (goalWindowTypes != nil) {
        queryParams[@"goalWindowTypes"] = goalWindowTypes;
    }

    id bodyParam = nil;
    NSMutableDictionary *formParams = [[NSMutableDictionary alloc] init];

    return [MHVRemoteMonitoringClient requestWithPath: resourcePath
                                    method: @"GET"
                                pathParams: pathParams
                               queryParams: queryParams
                                formParams: formParams
                                      body: bodyParam
                                   toClass: [MHVGoalRecommendationsResponse class]
                    //        responseType: [MHVGoalRecommendationsResponse* class]
                           completionBlock: ^(id data, NSError *error) {
                                if(handler) {
                                    handler((MHVGoalRecommendationsResponse*)data, error);
                                }
                            }];
}



@end
