//
// MHVOnboardingApi.m
// MHVLib
//
// Copyright (c) 2017 Microsoft Corporation. All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

/**
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import <Foundation/Foundation.h>
#import "MHVRemoteMonitoringClient.h"
#import "MHVClient.h"
#import "MHVOnboardingApi.h"
#import "MHVMicrosoftKhronosCloudCommonErrorsErrorResponse.h"
#import "MHVOnboardingRequest.h"
#import "MHVOnboardingResponse.h"


@implementation MHVRemoteMonitoringClient (MHVOnboardingApi)

NSString* kMHVOnboardingApiErrorDomain = @"MHVOnboardingApiErrorDomain";
NSInteger kMHVOnboardingApiMissingParamErrorCode = 234513;

#pragma mark - Api Methods

///
/// Onboard a user
/// 
///  @param onboardingRequest The meta data associated with an onboarding request 
///
///  @returns MHVOnboardingResponse*
///
+ (NSURLSessionTask*)generateInviteCodeWithOnboardingRequest: (MHVOnboardingRequest*) onboardingRequest
    completionHandler: (void (^ _Nonnull)(MHVOnboardingResponse* _Nullable output, NSError* _Nullable error)) handler {
    // verify the required parameter 'onboardingRequest' is set
    if (onboardingRequest == nil) {
        NSParameterAssert(onboardingRequest);
        if(handler) {
            NSDictionary * userInfo = @{NSLocalizedDescriptionKey : [NSString stringWithFormat:NSLocalizedString(@"Missing required parameter '%@'", nil),@"onboardingRequest"] };
            NSError* error = [NSError errorWithDomain:kMHVOnboardingApiErrorDomain code:kMHVOnboardingApiMissingParamErrorCode userInfo:userInfo];
            handler(nil, error);
        }
        return nil;
    }

    NSMutableString* resourcePath = [NSMutableString stringWithFormat:@"/Onboarding/GenerateInviteCode"];

    NSMutableDictionary *pathParams = [[NSMutableDictionary alloc] init];

    NSMutableDictionary* queryParams = [[NSMutableDictionary alloc] init];

    id bodyParam = nil;
    NSMutableDictionary *formParams = [[NSMutableDictionary alloc] init];
    bodyParam = onboardingRequest;

    return [MHVRemoteMonitoringClient requestWithPath: resourcePath
                                    method: @"POST"
                                pathParams: pathParams
                               queryParams: queryParams
                                formParams: formParams
                                      body: bodyParam
                                   toClass: [MHVOnboardingResponse class]
                    //        responseType: [MHVOnboardingResponse* class]
                           completionBlock: ^(id data, NSError *error) {
                                if(handler) {
                                    handler((MHVOnboardingResponse*)data, error);
                                }
                            }];
}



@end
