//
// MHVSleepsApi.m
// MHVLib
//
// Copyright (c) 2017 Microsoft Corporation. All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

/**
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import <Foundation/Foundation.h>
#import "MHVRemoteMonitoringClient.h"
#import "MHVClient.h"
#import "MHVSleepsApi.h"
#import "MHVMicrosoftKhronosCloudCommonErrorsErrorResponse.h"
#import "MHVSleepResponse.h"


@implementation MHVRemoteMonitoringClient (MHVSleepsApi)

NSString* kMHVSleepsApiErrorDomain = @"MHVSleepsApiErrorDomain";
NSInteger kMHVSleepsApiMissingParamErrorCode = 234513;

#pragma mark - Api Methods

///
/// Get the Sleep Activity data for this user by date range
/// 
///  @param startTime The ISO 8601 formatted start time of the Sleep activities, inclusive. (optional)
///
///  @param endTime The ISO 8601 formatted end time of the Sleep activities, exclusive.  Defaults to the current time in UTC. (optional)
///
///  @param includeDetails comma separated string to additional details. Available values Basic, Full. Default - Basic (optional)
///
///  @param maxPageSize The maximum number of entries to return per page.  Defaults to 31 (optional)
///
///  @returns MHVSleepResponse*
///
+ (NSURLSessionTask*)getSleepsWithStartTime: (NSDate*) startTime
    endTime: (NSDate*) endTime
    includeDetails: (NSString*) includeDetails
    maxPageSize: (NSNumber*) maxPageSize
    completionHandler: (void (^ _Nonnull)(MHVSleepResponse* _Nullable output, NSError* _Nullable error)) handler {
    NSMutableString* resourcePath = [NSMutableString stringWithFormat:@"/Sleeps"];

    NSMutableDictionary *pathParams = [[NSMutableDictionary alloc] init];

    NSMutableDictionary* queryParams = [[NSMutableDictionary alloc] init];
    if (startTime != nil) {
        queryParams[@"startTime"] = startTime;
    }
    if (endTime != nil) {
        queryParams[@"endTime"] = endTime;
    }
    if (includeDetails != nil) {
        queryParams[@"includeDetails"] = includeDetails;
    }
    if (maxPageSize != nil) {
        queryParams[@"maxPageSize"] = maxPageSize;
    }

    id bodyParam = nil;
    NSMutableDictionary *formParams = [[NSMutableDictionary alloc] init];

    return [MHVRemoteMonitoringClient requestWithPath: resourcePath
                                    method: @"GET"
                                pathParams: pathParams
                               queryParams: queryParams
                                formParams: formParams
                                      body: bodyParam
                                   toClass: [MHVSleepResponse class]
                    //        responseType: [MHVSleepResponse* class]
                           completionBlock: ^(id data, NSError *error) {
                                if(handler) {
                                    handler((MHVSleepResponse*)data, error);
                                }
                            }];
}



@end
