//
// MHVSleepsApi.h
// MHVLib
//
// Copyright (c) 2017 Microsoft Corporation. All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

/**
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import <Foundation/Foundation.h>
#import "MHVRemoteMonitoringClient.h"
#import "MHVMicrosoftKhronosCloudCommonErrorsErrorResponse.h"
#import "MHVSleepResponse.h"


NS_ASSUME_NONNULL_BEGIN

@interface MHVRemoteMonitoringClient (MHVSleepsApi)

/// Get the Sleep Activity data for this user by date range
/// 
///
/// @param startTime The ISO 8601 formatted start time of the Sleep activities, inclusive. (optional)
/// @param endTime The ISO 8601 formatted end time of the Sleep activities, exclusive.  Defaults to the current time in UTC. (optional)
/// @param includeDetails comma separated string to additional details. Available values Basic, Full. Default - Basic (optional)
/// @param maxPageSize The maximum number of entries to return per page.  Defaults to 31 (optional)
/// 
///  code:200 message:"OK",
///  code:0 message:"Error"
///
/// @return MHVSleepResponse*
+ (NSURLSessionTask* _Nullable)getSleepsWithStartTime: (NSDate* _Nullable) startTime
    endTime: (NSDate* _Nullable) endTime
    includeDetails: (NSString* _Nullable) includeDetails
    maxPageSize: (NSNumber* _Nullable) maxPageSize
    completionHandler: (void (^ _Nonnull)(MHVSleepResponse* _Nullable output, NSError* _Nullable error)) handler;



@end

NS_ASSUME_NONNULL_END
